apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxmox-metrics
  template:
    metadata:
      labels:
        app: proxmox-metrics
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"

    spec:
      containers:
      - name: proxmox-metrics
        image: steemax/proxmox-custom-scrape:v1.0.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /app/config/config.json
          subPath: config
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
      - name: config
        configMap:
          name: proxmox-metrics-config
