config:
  config: |
    {
      "server": "test-proxmox-k8s-01.el.wb.ru",
      "server_port": "8006",
      "protocol": "https",
      "token_uid": "poluboyarcev.a@infra-ldap!poluboyarcev.a",
      "token_secret": "6d669a6a-06dc-420f-809e-feed4b8e1aca",
      "scrape_timeout": 300
    }
kubernetesClusterDomain: cluster.local
proxmoxMetrics:
  proxmoxMetrics:
    image:
      repository: steemax/proxmox-custom-scrape
      tag: v1.0.0
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 20Mi
  replicas: 1
