apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxmox-metrics.fullname" . }}-config
  labels:
  {{- include "proxmox-metrics.labels" . | nindent 4 }}
data:
  config: {{ .Values.config.config | toYaml | indent 1 }}